[package]
name = "lang"
version = "0.1.0"
authors = ["Prabhakar Dev\" <ayushashi11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gc =" ^0.3.2"
gc_derive ="^0.3.2"
regex ="^1.3.4"